version: '3.7'

networks:
  blog_network:
    driver: bridge

services:

  blog_app:
    container_name: blog_app
    build: ./
    command: >
      sh -c "python manage.py collectstatic &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi -workers 4"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - blog_db
    networks:
      - blog_network

  blog_db:
    container_name: blog_db
    image: postgres:latest
    volumes:
      - blog_postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_HOST=${DB_HOST}
    networks:
      - blog_network

volumes:
  blog_postgres_data: