# Generated by Django 4.1 on 2022-08-29 09:07

from django.conf import settings
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs'),
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tags'),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.posts'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='blogs_posts_title_bfa9fb_gin'),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['created_at'], name='blogs_posts_created_01bc08_idx'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='blogs_blogs_title_18818b_gin'),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['created_at'], name='blogs_blogs_created_b35545_idx'),
        ),
    ]
