# Generated by Django 4.1 on 2022-09-02 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
